name = "rust-LAGC"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["RustLAGC"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = true

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.28.0"

[[require]]
name = "extended-derive-deceq"
git = "https://github.com/raoxiaojia/extended-derive-deceq"
rev = "main"

[[lean_lib]]
name = "RustLAGC"
